# Generated by Django 3.1.4 on 2021-03-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('pic', models.ImageField(upload_to='news_pics')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('pulished', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.journalist')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
