# Generated by Django 3.1.4 on 2021-03-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210326_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pulished',
            new_name='published',
        ),
    ]
