# Generated by Django 3.1.4 on 2021-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='news_pics'),
        ),
    ]
