# Generated by Django 3.1.4 on 2021-03-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210326_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('p', 'Politics'), ('s', 'Sports'), ('h', 'Health'), ('t', 'Technology'), ('e', 'Arts and Entertainment')], default='p', max_length=50),
        ),
    ]
