# Generated by Django 3.1.4 on 2021-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='reader',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
